spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    name: queue
    json_name: json_queue
  exchange:
    name: exchange
  routing:
    key: routing
    json_key: json_routing
